name: ml
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - numpy
  - pytorch-cuda
  - pandas
  - augmentor
  - ray
  - torchaudio
  - torchvision
  - pytorch-lightning
  - torchmetrics
  - pillow
  - pytorch
  - scikit-learn
