name: ml
channels:
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - pandas
  - scikit-learn
  - numpy
  - matplotlib
  - scipy
  - pytorch
  - lightning
  - pytorch-model-summary
  - python=3.10
  - ray-tune
